package main

import (
	"encoding/xml"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/kotaoue/combine-rss-feeds/internal/feed"
)

func main() {
	if err := Main(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func Main() error {
	feedsRaw := os.Getenv("INPUT_FEEDS")
	outputFile := os.Getenv("INPUT_OUTPUT_FILE")
	limitStr := os.Getenv("INPUT_LIMIT")
	feedTitle := os.Getenv("INPUT_FEED_TITLE")
	feedDesc := os.Getenv("INPUT_FEED_DESCRIPTION")

	if outputFile == "" {
		outputFile = "combined_feed.xml"
	}
	if feedTitle == "" {
		feedTitle = "Combined RSS Feed"
	}
	if feedDesc == "" {
		feedDesc = "Merged feed generated by combine-rss-feeds action"
	}

	limit := parseLimit(limitStr)
	feedURLs := parseFeedURLs(feedsRaw)

	if len(feedURLs) == 0 {
		return fmt.Errorf("no feed URLs provided in INPUT_FEEDS")
	}

	var allItems []feed.Item
	for _, u := range feedURLs {
		items, err := feed.Fetch(u)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: %v\n", err)
			continue
		}
		allItems = append(allItems, items...)
	}

	feed.SortItems(allItems)

	if limit > 0 && len(allItems) > limit {
		allItems = allItems[:limit]
	}

	rssFeed := feed.RSS(feedTitle, feedDesc, allItems)

	out, err := xml.MarshalIndent(rssFeed, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal XML: %w", err)
	}

	content := xml.Header + string(out) + "\n"

	if err := writeOutput(outputFile, content); err != nil {
		return err
	}

	fmt.Printf("Written %d items to %s\n", len(allItems), outputFile)
	return nil
}

func parseLimit(limitStr string) int {
	if limitStr == "" {
		return 10
	}
	if v, err := strconv.Atoi(strings.TrimSpace(limitStr)); err == nil && v > 0 {
		return v
	}
	return 10
}

func parseFeedURLs(feedsRaw string) []string {
	var feedURLs []string
	for _, line := range strings.Split(feedsRaw, "\n") {
		u := strings.TrimSpace(line)
		if u != "" {
			feedURLs = append(feedURLs, u)
		}
	}
	return feedURLs
}

// writeOutput writes content to outputFile, creating parent directories as needed.
func writeOutput(outputFile, content string) error {
	dir := filepath.Dir(outputFile)
	if dir != "." {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", dir, err)
		}
	}
	if err := os.WriteFile(outputFile, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", outputFile, err)
	}
	return nil
}
