package main

import (
	"encoding/xml"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/kotaoue/combine-rss-feeds/internal/build"
	"github.com/kotaoue/combine-rss-feeds/internal/fetch"
	"github.com/kotaoue/combine-rss-feeds/internal/parse"
)

func main() {
	feedsRaw := os.Getenv("INPUT_FEEDS")
	outputFile := os.Getenv("INPUT_OUTPUT_FILE")
	limitStr := os.Getenv("INPUT_LIMIT")
	feedTitle := os.Getenv("INPUT_FEED_TITLE")
	feedDesc := os.Getenv("INPUT_FEED_DESCRIPTION")

	if outputFile == "" {
		outputFile = "combined_feed.xml"
	}
	if feedTitle == "" {
		feedTitle = "Combined RSS Feed"
	}
	if feedDesc == "" {
		feedDesc = "Merged feed generated by combine-rss-feeds action"
	}

	limit := 10
	if limitStr != "" {
		if v, err := strconv.Atoi(strings.TrimSpace(limitStr)); err == nil && v > 0 {
			limit = v
		}
	}

	var feedURLs []string
	for _, line := range strings.Split(feedsRaw, "\n") {
		u := strings.TrimSpace(line)
		if u != "" {
			feedURLs = append(feedURLs, u)
		}
	}

	if len(feedURLs) == 0 {
		fmt.Fprintln(os.Stderr, "No feed URLs provided in INPUT_FEEDS")
		os.Exit(1)
	}

	var allItems []parse.Item
	for _, u := range feedURLs {
		items, err := fetch.Feed(u, limit)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: %v\n", err)
			continue
		}
		allItems = append(allItems, items...)
	}

	build.SortItems(allItems)

	feed := build.RSS(feedTitle, feedDesc, allItems)

	out, err := xml.MarshalIndent(feed, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to marshal XML: %v\n", err)
		os.Exit(1)
	}

	content := xml.Header + string(out) + "\n"

	// Ensure parent directories exist
	dir := filepath.Dir(outputFile)
	if dir != "." {
		if err := os.MkdirAll(dir, 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to create directory %s: %v\n", dir, err)
			os.Exit(1)
		}
	}

	if err := os.WriteFile(outputFile, []byte(content), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write %s: %v\n", outputFile, err)
		os.Exit(1)
	}

	fmt.Printf("Written %d items to %s\n", len(allItems), outputFile)
}

